included:
  - Sources

disabled_rules: 
  - line_length
  - identifier_name
  - type_name
  - file_length
  - type_body_length
  - function_body_length


nesting:
    type_level: 4


custom_rules:
  trojan_source:
    regex: "[\u202A\u202B\u202D\u202E\u2066\u2067\u2068\u202C\u2069]"
    severity: error
    message: "Source should not contain characters that may be used in reordering attacks. https://trojansource.codes/trojan-source.pdf"

reporter: "xcode"
